apiVersion: apps/v1
kind: Deployment
metadata:
  name: dadjokeapi-deployment
  labels:
    app: dadjokeapi
spec:
  selector:
    matchLabels:
      app: dadjokeapi
  template:
    metadata:
      labels:
        app: dadjokeapi
    spec:
      containers:
      - name: dadjokeapi
        image: maxhorstmann/dadjokeapi:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dadjokeapi-service
spec:
  selector:
    app: dadjokeapi
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer